// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccount = "Account"

// Account mapped from table <Account>
type Account struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name     string `gorm:"column:name" json:"name"`
	Nickname string `gorm:"column:nickname" json:"nickname"`
	Password string `gorm:"column:password" json:"password"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
