// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBlock = "block"

// Block mapped from table <block>
type Block struct {
	Key    string `gorm:"column:key;primaryKey" json:"key"`
	GoodID string `gorm:"column:good_id;not null" json:"good_id"`
}

// TableName Block's table name
func (*Block) TableName() string {
	return TableNameBlock
}
