// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItem = "Item"

// Item mapped from table <Item>
type Item struct {
	ID int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
}

// TableName Item's table name
func (*Item) TableName() string {
	return TableNameItem
}
